// <auto-generated />
using System;
using LolaSoft.WebShop.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LolaSoft.WebShop.DataAccess.Migrations
{
    [DbContext(typeof(WebShopDbContext))]
    partial class WebShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, Name = "Clothes" },
                        new { Id = 2, Name = "Pet" },
                        new { Id = 3, Name = "House" }
                    );
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("StockQuantity");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 1, DateTimeKind.Local), Name = "Jacket", Price = 12.2m, StockQuantity = 42 },
                        new { Id = 2, CategoryId = 1, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "Shirt", Price = 10.2m, StockQuantity = 11 },
                        new { Id = 3, CategoryId = 1, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "Sweater", Price = 25.2m, StockQuantity = 35 },
                        new { Id = 4, CategoryId = 2, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "Dog Toy", Price = 3.2m, StockQuantity = 18 },
                        new { Id = 5, CategoryId = 2, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "Bowl", Price = 1.2m, StockQuantity = 15 },
                        new { Id = 6, CategoryId = 3, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "Fork", Price = 2.2m, StockQuantity = 25 },
                        new { Id = 7, CategoryId = 3, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "wash mashine", Price = 122.5m, StockQuantity = 41 },
                        new { Id = 8, CategoryId = 3, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "knife", Price = 1.5m, StockQuantity = 30 },
                        new { Id = 9, CategoryId = 3, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "spoon", Price = 1.4m, StockQuantity = 38 },
                        new { Id = 10, CategoryId = 3, CreatedOn = new DateTime(2020, 1, 5, 1, 25, 33, 4, DateTimeKind.Local), Name = "dinner table", Price = 65.5m, StockQuantity = 47 }
                    );
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Category", b =>
                {
                    b.HasOne("LolaSoft.WebShop.DataAccess.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Order", b =>
                {
                    b.HasOne("LolaSoft.WebShop.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.OrderItem", b =>
                {
                    b.HasOne("LolaSoft.WebShop.DataAccess.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LolaSoft.WebShop.DataAccess.Models.Product", b =>
                {
                    b.HasOne("LolaSoft.WebShop.DataAccess.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
